name: Build/Publish LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tharris_cv.tex

      - name: Convert PDF to PNG (Poppler)
        run: |
          sudo apt-get install -y poppler-utils
          pdftoppm tharris_cv.pdf tharris_cv -png -singlefile
          ls -l tharris_cv*

      - name: Publish to site with SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: tharris_cv.p*
          target: public_html/resume
